name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore ./Ocefara
    - name: Build
      run: dotnet build ./Ocefara --configuration Release --no-restore
    
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.3.0
      
     - name: Test
      run: dotnet test ./Ocefara --no-restore --verbosity normal