name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore ./Ocefara
    - name: Build
      run: dotnet build ./Ocefara --configuration Release --no-restore
    - name: Create mongo Docker container
      uses: DigiPie/mongo-action@v1.0.0
      with:
        image-version: latest
        port: 27017
    - name: Install mongodb-clients
      id: install_mongodb_clients
      run: sudo apt install mongodb-clients
    - name: Test
      run: dotnet test ./Ocefara --no-restore --verbosity normal